Pet4You/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from pet4you_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pet4you_app/', include("pet4you_app.urls")),
    path("", views.home, name="home"),
] + static(settings.STATIC_URL)

pet4you_app/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "pet4you"
urlpatterns = [
    path("", views.home, name="home"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register_view, name='register'),
    path("posting/", views.createPost, name="posting"),
    path("report_list/", views.list_reports, name="report_list"),
    path("report/<int:pet_id>/", views.add_report, name='report'),
    path("report_admin/<int:report_id>/", views.report_admin_view, name='report_admin'),
    path("list/", views.listPets, name= "list"),
    path("favorite/", views.listFavorites, name= "favorite"),
    path("edit/<int:pet_id>/", views.edit_post, name="edit_post"),
    path('favoritar_pet/<int:pet_id>/', views.favoritar_pet, name='favoritar_pet'),
    path('desfavoritar_pet/<int:pet_id>/', views.desfavoritar_pet, name='desfavoritar_pet'),
    path('listar_pets/', views.listar_pets, name='listar_pets'),
    path('delete/<int:pet_id>/', views.delete_post, name='delete_post'),
    path('api/create_admin/', views.create_admin_user, name='create_admin_user'),
    path('pets/<int:pet_id>/vaccine_card/', views.vaccine_card, name='vaccine_card'),
    path('pets/<int:pet_id>/vaccine_add/', views.vaccine_add, name='vaccine_add'),
    path('download_pet/<int:pet_id>/', views.download_pet, name='download_pet'),
    path("delete_as_user/<int:pet_id>/", views.delete_post_as_user, name="delete_post_as_user"),
    path('adopt/<int:pet_id>/', views.adopt_pet, name='adopt_pet'),



    
]

pet4you_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Pet(models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=50)
    breed = models.CharField(max_length=50)
    age = models.PositiveIntegerField(null=True)
    description = models.TextField(null=True)
    photo = models.CharField(max_length=500, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    favorited = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Vaccine(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, related_name='vaccines')
    name = models.CharField(max_length=100)
    date = models.DateField()
    next_due_date = models.DateField(blank=True, null=True)
    
    def __str__(self):
        return f"{self.name} para {self.pet.name} em {self.date}"
    
class Report(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    reporter = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Report #{self.id} - {self.pet}"
    

pet4you_app/forms.py
# forms.py
from django import forms
from .models import Vaccine
import datetime
from django.core.exceptions import ValidationError

class VaccineForm(forms.ModelForm):
    class Meta:
        model = Vaccine
        fields = ['name', 'date', 'next_due_date']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'next_due_date': forms.DateInput(attrs={'type': 'date'}),
        }
        
    def clean_date(self):
        date = self.cleaned_data['date']
        if date > datetime.date.today():
            raise ValidationError("A data da vacina não pode ser futura.")
        return date

    def clean_next_due_date(self):
        next_due_date = self.cleaned_data['next_due_date']
        if next_due_date != None and next_due_date < datetime.date.today():
            raise ValidationError("A próxima dose não pode ser uma data passada.")
        return next_due_date

class PetFilterForm(forms.Form):
    species = forms.CharField(max_length=100, required=False)
    breed = forms.CharField(max_length=100, required=False)
    age = forms.IntegerField(required=False)
    name = forms.CharField(max_length=100, required=False) 
    
    

pet4you_app/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout as auth_logout
from django.db.models import Q
from .models import Pet
from .models import Report
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User
from .forms import PetFilterForm
from .forms import VaccineForm
from django.utils import timezone
from datetime import timedelta
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from django.conf import settings
import os
import urllib.request
from PIL import Image as PILImage
import platform
if platform.system() == "Windows":
    from winotify import Notification
    import winreg
else:
    Notification = None

def new_notification(msg):
    print(f"Notification: {msg}")
    if Notification:
        notificacao = Notification(app_id="Pet4You", title=msg)
        notificacao.show()


def notify_new_pets_last_24_hours():
    now = timezone.now()
    ultimas_24horas = now - timedelta(hours=24)
    new_pets_count = Pet.objects.filter(created_at__gte=ultimas_24horas).count()
    print(f"Número de pets criados nas últimas 24 horas: {new_pets_count}")
    if Notification:
        new_notification(f"Número de pets criados nas últimas 24 horas: {new_pets_count}")
    
@csrf_exempt
@require_POST
def create_admin_user(request):
    username = "anton"
    password = "123456"
    if not User.objects.filter(username=username).exists():
        user = User.objects.create_superuser(username=username, email='admin@example.com', password=password)
        user.save()
        return JsonResponse({'status': 'admin_created'})
    else:
        return JsonResponse({'status': 'admin_exists'})
    
def download_pet(request,pet_id):
    pet = get_object_or_404(Pet, id=pet_id)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{pet.name}.pdf"'

    p = canvas.Canvas(response, pagesize=letter)
    width, height = letter

    # Título
    title = "Informações do Pet"
    p.setFont("Helvetica-Bold", 20)
    text_width = p.stringWidth(title, "Helvetica-Bold", 20)
    p.drawString((width - text_width) / 2, height - 50, title)

    # Imagem
    if pet.photo:
        photo_url = pet.photo
        
        try:
            image = ImageReader(photo_url)
            p.drawImage(image, (width - 150) / 2, height - 250, width=150, height=150)
        except Exception as e:
            print(f"Error loading image from URL: {e}")
            p.setFont("Helvetica", 12)
            #p.drawString(100, height - 250, "Imagem não disponível")
            text_width = p.stringWidth("Imagem não disponível", "Helvetica-Bold", 20)
            p.drawString((width - text_width) / 2, height - 250, "Imagem não disponível")
            

    # Detalhes
    p.setFont("Helvetica-Bold", 12)
    y_position = height - 340
    p.drawString(100, y_position, f"Nome: {pet.name}")
    p.setFont("Helvetica", 12)
    p.drawString(100, y_position - 30, f"Espécie: {pet.species}")
    p.drawString(100, y_position - 60, f"Raça: {pet.breed}")
    p.drawString(100, y_position - 90, f"Idade: {pet.age}")
    p.drawString(100, y_position - 120, f"Descrição: {pet.description}")

    p.showPage()
    p.save()

    return response
    
def vaccine_card(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)
    vaccines = pet.vaccines.all()
    return render(request, 'vaccine_card.html', {'pet': pet, 'vaccines': vaccines})

def vaccine_add(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)
    
    if request.method == 'POST':
        form = VaccineForm(request.POST)
        if form.is_valid():
            vaccine = form.save(commit=False)
            vaccine.pet = pet
            vaccine.save()
            return redirect('pet4you:vaccine_card', pet_id=pet.id)
    else:
        form = VaccineForm()
    
    return render(request, 'vaccine_add.html', {'form': form, 'pet': pet})

def createPost(request):
   p = Pet.objects.all()
   if(request.method == 'POST'):
       name = request.POST.get('name')
       species = request.POST.get('species')
       breed = request.POST.get('breed')
       age = request.POST.get('age')
       description = request.POST.get('description')
       photo = request.POST.get('photo')
       owner = request.user
       
       #Validation:
       errors = {}
       if not photo:
            errors['photo'] = 'Photo is required.'
       if not name:
            errors['name'] = 'Name is required.'
       if not age:
            errors['age'] = 'Age is required.'
       if not breed:
            errors['breed'] = 'Breed is required'
       if not species:
            errors['species'] = 'Species is required'
       if age != '':
           if int(age) > 99:
             errors['age'] = 'Age has to be under 99'

       if errors:
            return render(request, 'posting.html', {'errors': errors})
        
       pet = Pet(name=name, species=species,breed=breed,age=age,description=description, photo=photo,created_at='',owner=owner,favorited=False)
       pet.save()
       new_notification("Post adicionado com sucesso!")
       return redirect("pet4you:home")
   else:
       return render(request, 'posting.html')

def favoritar_pet(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)
    if(pet.favorited == False):
        new_notification("Post favoritado com sucesso")
        pet.favorited = True
    else:
        new_notification("Post desfavoritado com sucesso")
        pet.favorited = False
    pet.save()
    return redirect('pet4you:home')

def desfavoritar_pet(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)
    pet.favorited = False
    pet.save()
    new_notification("Post desfavoritado com sucesso")
    return redirect('pet4you:favorite')

def listPets(request):
    user = request.user 
    pets = Pet.objects.filter(owner=user)
    return render(request, 'list.html', {'pets': pets})

def listFavorites(request):
    user = request.user 
    pets = Pet.objects.filter(favorited=True)
    return render(request, 'favorite.html', {'pets': pets})

def add_report(request, pet_id):
    reports = Report.objects.all()
    pet = get_object_or_404(Pet, pk=pet_id)
    if(request.method == 'POST'):
        text = request.POST.get('text')
        reporter = request.user
        report = Report(reporter=reporter,pet=pet, text=text)
        report.save()
        new_notification("Post reportado com sucesso")
        return redirect("pet4you:home")
    else:
        return render(request, 'report.html', {'pet': pet})

def report_admin_view(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    pet = report.pet
    return render(request, 'report_admin.html', {'report': report, 'pet': pet})



def list_reports(request):
    reports = Report.objects.all()
    return render(request, 'report_list.html', {'reports' : reports} )


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                notify_new_pets_last_24_hours()
                return redirect('home')  
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            notify_new_pets_last_24_hours()
            return redirect('home')  
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

def logout(request):
    auth_logout(request)
    new_notification("Logout Realizado")
    return redirect('home')


def home(request):
    species = request.GET.get('especie')
    breed = request.GET.get('raca')
    name = request.GET.get('nome')
    age = request.GET.get('idade')

    pets_para_adocao = Pet.objects.all()

    if species:
        pets_para_adocao = pets_para_adocao.filter(species=species)
    if breed:
        pets_para_adocao = pets_para_adocao.filter(breed=breed)
    if name:
        pets_para_adocao = pets_para_adocao.filter(name=name)
    if age:
        pets_para_adocao = pets_para_adocao.filter(age=age)

    return render(request, 'home.html', {'pets_para_adocao': pets_para_adocao})

def edit_post(request, pet_id):
  
    pet = get_object_or_404(Pet, pk=pet_id)

    if request.method == 'POST':
        name = request.POST.get('name')
        species = request.POST.get('species')
        breed = request.POST.get('breed')
        age = request.POST.get('age')
        description = request.POST.get('description')
        photo = request.POST.get('photo')
        owner = request.user
        
         #Validation:
        errors = {}
        if not photo:
            errors['photo'] = 'Photo is required.'
        if not name:

pet4you_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet4You</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?">

</head>

<body>

    {% block body%}
    {% endblock %}
</body>

</html>

pet4you_app/templates/favorite.html
{% extends "base.html" %} 
{% load static %}
{% block body %}

<style>
  body {
    background-color: #999999; /* Cor de fundo bege */
  }

  .banner {
    background-color: #999999; /* Cor de fundo bege */
  }

  .container {
    max-width: 800px; /* Define a largura máxima do contêiner */
    margin: 0 auto; /* Centraliza o contêiner na página */
  }

  .content {
    display: flex; /* Faz com que os itens fiquem lado a lado */
    flex-wrap: wrap; /* Permite que os itens quebrem para a próxima linha quando não há espaço suficiente */
    justify-content: center; /* Centraliza os itens horizontalmente */
  }

  .pet-item {
    display: flex;
    flex-direction: column; /* Alinha os itens verticalmente */
    align-items: center; /* Centraliza os itens verticalmente */
    margin: 20px; /* Adiciona espaçamento entre os itens */
    background-color: white; /* Define o fundo branco */
    padding: 20px; /* Adiciona espaço interno */
    border-radius: 8px; /* Adiciona cantos arredondados */
    width: 200px; /* Define a largura dos contêineres dos animais */
  }

  .pet-item img {
    width: 100px; /* Define o tamanho da imagem */
    height: 100px; /* Define o tamanho da imagem */
    margin-bottom: 0px; /* Adiciona espaçamento abaixo da imagem */
  }
</style>

<header class="home-header" style="height: 80px; display: flex; align-items: center; background-color: white;">
  <div class="container" style="display: flex; align-items: center; justify-content: space-between; width: 100%;">
    <a href="{% url 'pet4you:home' %}">
      <img src="{% static 'css/icon-removebg.png' %}" alt="Logo" class="logo-icon" width="150" height="150" style="margin-right: 10px;">
    </a>
    <nav class="home-nav" style="margin-left: auto;">
      <ul style="display: flex; gap: 10px;">
        {% if user.is_authenticated %}
        <li><a href="{% url 'pet4you:posting' %}" class="nav-link" style="color: #004261;">Postar Anúncio</a></li>
        <li><a href="{% url 'pet4you:list' %}" class="nav-link" style="color: #004261;">Meus Anúncios</a></li>
        <li><a href="{% url 'pet4you:favorite' %}" class="nav-link" style="color: #004261;">Meus Favoritos</a></li>
        {% if user.is_staff %}
        <li><a href="{% url 'pet4you:report_list' %}" class="nav-link" style="color: #004261;">Denúncias</a></li>
        {% endif %}
        {% csrf_token %}
        <li><a href="{% url 'pet4you:logout' %}" class="nav-link" style="color: #004261;">Logout</a></li>
        {% else %}
        <li><a href="{% url 'pet4you:login' %}" class="nav-link" style="color: #004261;">Login</a></li>
        <li><a href="{% url 'pet4you:register' %}" class="nav-link" style="color: #004261;">Sign up</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>
</header>

<section class="content">
  <div class="container">
    <h1 style="text-align: center;">Your Favorited Pets</h1>
    <div class="register-link" style="display: flex; justify-content: center;">
        <p style="margin: 20px 0;"><a href="{% url 'pet4you:home' %}" style="text-decoration: none;">Voltar para a Home</a></p>
      </div>
      
    {% if pets %}
    <div class="content">
        {% for pet in pets %}
        <div class="pet-item">
            <img src="{{pet.photo}}" alt="" height="100">
            <div style="text-align: center;">
                <h3>{{ pet.name }}</h3>
                <p>Species: {{ pet.species }}</p>
                <p>Breed: {{ pet.breed }}</p>
                <p>Age: {{ pet.age }}</p>
                <p>Description: {{ pet.description }}</p> <br>
                <form method="post" action="{% url 'pet4you:desfavoritar_pet' pet.id %}">
                  {% csrf_token %}
                  <button type="submit" style="background-color: #004261; color: white; border-radius: 5px; padding: 8px 15px;">Desfavoritar</button>
                </form>
                <form method="post" action="{% url 'pet4you:favoritar_pet' pet.id %}">

                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
  </div>
</section>


<footer class="home-footer">
  <div class="container">
    <p>&copy; 2024 Pet4You. Todos os direitos reservados.</p>
  </div>
</footer>

<script>
  document.querySelectorAll('.nav-link').forEach(link => {
    link.addEventListener('click', () => {
        link.classList.add('clicked');
        document.querySelectorAll('.nav-link').forEach(otherLink => {
            if (otherLink !== link) {
                otherLink.classList.remove('clicked');
            }
        });
    });
  });
</script>

{% endblock %}

pet4you_app/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block body %}

<style>
  body {
    background-color: #999999; /* Cor de fundo bege */
  }

  .banner {
    background-color: #999999; /* Cor de fundo bege */
  }
  
</style>
<header class="home-header" style="height: 80px; display: flex; align-items: center; background-color: white;">
  <div class="container" style="display: flex; align-items: center; justify-content: space-between; width: 100%;">
    <a href="{% url 'pet4you:home' %}">
      <img src="{% static 'css/icon-removebg.png' %}" alt="Logo" class="logo-icon" width="150" height="150" style="margin-right: 10px;">
    </a>
    <nav class="home-nav" style="margin-left: auto;">
      <ul style="display: flex; gap: 10px;">
        {% if user.is_authenticated %}
        <li><a href="{% url 'pet4you:posting' %}" class="nav-link" style="color: #004261;">Postar Anúncio</a></li>
        <li><a href="{% url 'pet4you:list' %}" class="nav-link" style="color: #004261;">Meus Anúncios</a></li>
        <li><a href="{% url 'pet4you:favorite' %}" class="nav-link" style="color: #004261;">Meus Favoritos</a></li>
        {% if user.is_staff %}
        <li><a href="{% url 'pet4you:report_list' %}" class="nav-link" style="color: #004261;">Denúncias</a></li>
        {% endif %}
        {% csrf_token %}
        <li><a href="{% url 'pet4you:logout' %}" class="nav-link" style="color: #004261;">Logout</a></li>
        {% else %}
        <li><a href="{% url 'pet4you:login' %}" class="nav-link" style="color: #004261;">Login</a></li>
        <li><a href="{% url 'pet4you:register' %}" class="nav-link" style="color: #004261;">Sign up</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>
</header>

<section class="banner">
  <div class="container" style="background-color: #; padding: 20px;"> 
    <h2 style="color: #004261;">Bem-vindo ao Pet4You!</h2> 
    <a href="#" class="btn" style="background-color: #004261; color: white;">Encontre seu pet</a>
  </div>
</section>

<section class="content">
  <div class="container">
    <h2>Confira os pets disponíveis para adoção:</h2>

    <form method="GET" action="{% url 'pet4you:home' %}">
      <input type="text" name="especie" placeholder="Especie">
      <input type="text" name="raca" placeholder="Raça">
      <input type="text" name="nome" placeholder="Nome">
      <input type="text" name="idade" placeholder="Idade">
      <input type="submit" value="Filtrar">
    </form>

    <div class="services">
      {% for pet in pets_para_adocao %}
      <div class="service">
        <img src="{{pet.photo}}" alt="" width="100" height="100">
        <h3>{{ pet.name }}</h3>
        <h4>Raça: {{ pet.breed }}</h4>
        <h4>Espécie: {{ pet.species }}</h4>
        <h4>Idade: {{ pet.age }}</h4>
        <p>Descrição: {{ pet.description }}</p>
        <a class='button-2' href="{% url 'pet4you:report' pet.id %}" style="background-color: #004261; color: white;">Reportar</a></br>
        <a class='button-2' href="{% url 'pet4you:adopt_pet' pet.id %}" style="background-color: #004261; color: white;">Adotar</a></br>
        <form method="post" action="{% url 'pet4you:favoritar_pet' pet.id %}">
            {% csrf_token %}
            {% if pet.favorited %}
                <button type="submit" class="button-2" style="background-color: #004261; color: white;">Desfavoritar</button>
            {% else %}
                <button type="submit" class="button-2" style="background-color: #004261; color: white;">Favoritar</button>
            {% endif %}
        </form></br>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<footer class="home-footer">
  <div class="container">
    <p>&copy; 2024 Pet4You. Todos os direitos reservados.</p>
  </div>
</footer>

<script>
  document.querySelectorAll('.nav-link').forEach(link => {
    link.addEventListener('click', () => {
        link.classList.add('clicked');
        document.querySelectorAll('.nav-link').forEach(otherLink => {
            if (otherLink !== link) {
                otherLink.classList.remove('clicked');
            }
        });
    });
  });
</script>

{% endblock %}

pet4you_app/templates/list.html
{% extends "base.html" %} 
{% load static %}
{% block body %}

<style>
  body {
    background-color: #999999; /* Cor de fundo bege */
  }

  .banner {
    background-color: #999999; /* Cor de fundo bege */
  }

  .container {
    max-width: 800px; /* Define a largura máxima do contêiner */
    margin: 0 auto; /* Centraliza o contêiner na página */
  }

  .content {
    display: flex; /* Faz com que os itens fiquem lado a lado */
    flex-wrap: wrap; /* Permite que os itens quebrem para a próxima linha quando não há espaço suficiente */
    justify-content: center; /* Centraliza os itens horizontalmente */
  }

  .pet-item {
    display: flex;
    flex-direction: column; /* Alinha os itens verticalmente */
    align-items: center; /* Centraliza os itens verticalmente */
    margin: 20px; /* Adiciona espaçamento entre os itens */
    background-color: white; /* Define o fundo branco */
    padding: 20px; /* Adiciona espaço interno */
    border-radius: 8px; /* Adiciona cantos arredondados */
    width: 200px; /* Define a largura dos contêineres dos animais */
  }

  .pet-item img {
    width: 100px; /* Define o tamanho da imagem */
    height: 100px; /* Define o tamanho da imagem */
    margin-bottom: 10px; /* Adiciona espaçamento abaixo da imagem */
  }

  .register-link {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 0px; /* Adiciona margem inferior */
  }
</style>

<header class="home-header" style="height: 80px; display: flex; align-items: center; background-color: white;">
  <div class="container" style="display: flex; align-items: center; justify-content: space-between; width: 100%;">
    <a href="{% url 'pet4you:home' %}">
      <img src="{% static 'css/icon-removebg.png' %}" alt="Logo" class="logo-icon" width="150" height="150" style="margin-right: 10px;">
    </a>
    <nav class="home-nav" style="margin-left: auto;">
      <ul style="display: flex; gap: 10px;">
        {% if user.is_authenticated %}
        <li><a href="{% url 'pet4you:posting' %}" class="nav-link" style="color: #004261;">Postar Anúncio</a></li>
        <li><a href="{% url 'pet4you:list' %}" class="nav-link" style="color: #004261;">Meus Anúncios</a></li>
        <li><a href="{% url 'pet4you:favorite' %}" class="nav-link" style="color: #004261;">Meus Favoritos</a></li>
        {% if user.is_staff %}
        <li><a href="{% url 'pet4you:report_list' %}" class="nav-link" style="color: #004261;">Denúncias</a></li>
        {% endif %}
        {% csrf_token %}
        <li><a href="{% url 'pet4you:logout' %}" class="nav-link" style="color: #004261;">Logout</a></li>
        {% else %}
        <li><a href="{% url 'pet4you:login' %}" class="nav-link" style="color: #004261;">Login</a></li>
        <li><a href="{% url 'pet4you:register' %}" class="nav-link" style="color: #004261;">Sign up</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>
</header>

<section class="content">
  <div class="container">
    <h1 style="text-align: center;">Your Pets</h1>
    <div class="register-link" style="display: flex; justify-content: center;">
        <p style="margin: 20px 0;"><a href="{% url 'pet4you:home' %}" style="text-decoration: none;">Voltar para a Home</a></p>
      </div>


    {% if pets %}
    <div class="content">
        {% for pet in pets %}
        <div class="pet-item">
            <img src="{{pet.photo}}" alt="" height="100">
            <div style="text-align: center;">
                <h3>{{ pet.name }}</h3>
                <p>Species: {{ pet.species }}</p>
                <p>Breed: {{ pet.breed }}</p>
                <p>Age: {{ pet.age }}</p>
                <p>Description: {{ pet.description }}</p><br>
                <a class='button-2'href="{% url 'pet4you:edit_post' pet.id %}" style="background-color: #004261; color: white; padding: 2px;">Editar</a>
                <a class='button-2'href="{% url 'pet4you:vaccine_card' pet.id %}" style="background-color: #004261; color: white; margin-top: 10px; padding: 2px;">Vacinas</a>
                <a class='button-2'href="{% url 'pet4you:delete_post_as_user' pet.id %}" style="background-color: #004261; color: white; margin-top: 10px; padding: 2px;">Remover</a>  
              </form>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
  </div>
</section>



<footer class="home-footer">
  <div class="container">
    <p>&copy; 2024 Pet4You. Todos os direitos reservados.</p>
  </div>
</footer>

<script>
  document.querySelectorAll('.nav-link').forEach(link => {
    link.addEventListener('click', () => {
        link.classList.add('clicked');
        document.querySelectorAll('.nav-link').forEach(otherLink => {
            if (otherLink !== link) {
                otherLink.classList.remove('clicked');
            }
        });
    });
  });
</script>

{% endblock %}

pet4you_app/templates/listarpet.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listagem de Pets</title>
</head>
<body>
    <h1>Listagem de Pets</h1>
    <ul>
        {% for pet in pets %}
            <li>{{ pet.name }} - {{ pet.species }} - {{ pet.breed }} - {{ pet.age }}</li>
        {% endfor %}
    </ul>
</body>
</html>